// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: single_ui

#include "ui.h"
#include <stdio.h>

unsigned char tux_index = 0;
void change_image(lv_event_t * e)
{
	if(tux_index == 0){
	  lv_img_set_src(ui_Tuxicon, &ui_img_tux_png);
	  tux_index = 1;
	}
	else {
	  lv_img_set_src(ui_Tuxicon, &ui_img_tux2_png);
	  tux_index = 0;
	}
}

void unchecked(lv_event_t * e)
{
	lv_img_set_src(ui_Tuxicon, &ui_img_tux_png);
}

void checked(lv_event_t * e)
{
	lv_img_set_src(ui_Tuxicon, &ui_img_tux2_png);
}
